In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
# Q1: Open Your CSV file and print the first 10 rows in a good format

data = pd.read_csv("tmdb_5000_movies.csv")                   # will read the file
data.head(10)                                               # Printing the first 10 rows

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.batmanvsupermandawnofjustice.com/,209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-23,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004

In [3]:
# Q2-P1: search for NAN Value 

#True â†’ Missing (NaN) value
#False â†’ Non-missing value
data.isna().sum() #sum will get data per column without it will give me the whole sheet

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [4]:
# Q2-P2: Replace Missing Values with the word Missing

data.replace(np.nan , "Missing" , inplace = True)

In [ ]:
# Q3: Discover the types of each columns and modify them if needed

data.info ()                                               #summary of a DataFrame

In [ ]:
data.columns                                          #Getting columns names

In [ ]:
# Convert 'release_date' to datetime format

data['release_date'] = pd.to_datetime(data['release_date'], errors='coerce')

# Convert runtime to numeric (non-numeric values will become NaN)
data['runtime'] = pd.to_numeric(data['runtime'], errors='coerce')

In [5]:
# Q4: Statistical Overview

print("\nDescriptive statistics:")
print(data.describe())

Descriptive statistics:
             budget             id   popularity       revenue  vote_average  \
count  4.803000e+03    4803.000000  4803.000000  4.803000e+03   4803.000000
mean   2.904504e+07   57165.484281    21.492301  8.226064e+07      6.092172
std    4.072239e+07   88694.614033    31.816650  1.628571e+08      1.194612
min    0.000000e+00       5.000000     0.000000  0.000000e+00      0.000000
25%    7.900000e+05    9014.500000     4.668070  0.000000e+00      5.600000
50%    1.500000e+07   14629.000000    12.921594  1.917000e+07      6.200000
75%    4.000000e+07   58610.500000    28.313505  9.291719e+07      6.800000
max    3.800000e+08  459488.000000   875.581305  2.787965e+09     10.000000

         vote_count
count   4803.000000
mean     690.217989
std     1234.585891
min        0.000000
25%       54.000000
50%      235.000000
75%      737.000000
max    13752.000000

In [ ]:
# Q5: Calculate the mean rate for [1999, 1980, 2004, 2017] the movies grouped by years

# Extract the release year from the datetime column
data['release_year'] = data['release_date'].dt.year

# Define the years of interest
target_years = [1999, 1980, 2004, 2017]

# Filter the dataset for those years
filtered_data = data[data['release_year'].isin(target_years)]

# Group by release_year and calculate the mean of vote_average
mean_vote_by_year = filtered_data.groupby('release_year')['vote_average'].mean()

# Display the result
print("Mean vote average for the selected years:")
print(mean_vote_by_year)

In [ ]:
# Q6: Rearange the dataframe based on revenue - budget values 

# Calculate 'profit' as revenue - budget
data['profit'] = data['revenue'] - data['budget']

# Sort the DataFrame by 'profit' in descending order
data_sorted_by_profit = data.sort_values(by='profit', ascending=False)
data_sorted_by_profit = data_sorted_by_profit.reset_index(drop=True)  #to remove the original file index from the results 

# Display the top 5 rows to verify
print(data_sorted_by_profit[['title', 'budget', 'revenue', 'profit']].head())

In [ ]:
# Q7: Allocate the year with the largest movies released in ['Action', 'Romance']

#sheet already loaded 
#dates already converted to datatime 

import ast 

# Convert genre strings to lists of dictionaries
data['genres'] = data['genres'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Extract only the genre names into a list
data['genre_names'] = data['genres'].apply(lambda x: [d['name'] for d in x])

# Filter for movies that have 'Action' or 'Romance' in genre_names
action_romance = data[data['genre_names'].apply(lambda genres: 'Action' in genres or 'Romance' in genres)]

# Count movies per release_year
year_counts = action_romance['release_year'].value_counts()

# Get the year with the maximum count
top_year = year_counts.idxmax()
top_count = year_counts.max()

print(f"The year with the most 'Action' or 'Romance' movies is: {int(top_year)} ({top_count} movies)")

# Add bar chart
plt.figure(figsize=(12, 6))
plt.bar(year_counts.index, year_counts.values, color='coral')
plt.xlabel('Release Year')
plt.ylabel('Number of Action or Romance Movies')
plt.title(" Number of Action or Romance Movies Released per Year")
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

In [ ]:
# Q8: Find the movies with top 5 revenue - budget value

#sheet already loaded 
#profit already calculated in Q6

# Sort the data by profit in descending order
sorted_by_profit = data.sort_values(by='profit', ascending=False).reset_index(drop=True)

# Select the top 5 movies with the highest profit
top_5_profitable_movies = sorted_by_profit[['title', 'budget', 'revenue', 'profit']].head(5)

# Display the result
print("Top 5 movies by profit (revenue - budget):")
print(top_5_profitable_movies)

#Visualize the top 5 profitable movies
plt.figure(figsize=(10, 6))
plt.barh(top_5_profitable_movies['title'][::-1], top_5_profitable_movies['profit'][::-1], color='green')
plt.xlabel("Profit (USD)")
plt.title("Top 5 Most Profitable Movies")
plt.tight_layout()
plt.show()

In [ ]:
# Q9: Find the year with the highest number of movies release

#sheet already loaded
#dates already converted to datatime 

# Count the number of movies released per year
movie_counts_per_year = data['release_year'].value_counts()

# Find the year with the most movies
top_year = int(movie_counts_per_year.idxmax())
top_count = movie_counts_per_year.max()

# Display result
print(f"The year with the highest number of movie releases is: {top_year} ({top_count} movies)")

# Plotting the result
plt.figure(figsize=(12, 6))
plt.bar(movie_counts_per_year.index, movie_counts_per_year.values, color='skyblue')
plt.xlabel("Release Year")
plt.ylabel("Number of Movies Released")
plt.title("Number of Movies Released Per Year")
plt.tight_layout()
plt.show()

In [ ]:
# Q10: Find the top 2 countries with the highest production movies number

#import Counter to be able to count
from collections import Counter

# Convert 'production_countries' from string to list of dictionaries
data['production_countries'] = data['production_countries'].apply(lambda x: eval(x) if isinstance(x, str) else [])

# Extract country names
data['country_names'] = data['production_countries'].apply(lambda x: [d['name'] for d in x if 'name' in d])

# Count all country names
country_counter = Counter()
for country_list in data['country_names']:
    country_counter.update(country_list)

# Display the top 2 countries
print("Top 2 countries with the most produced movies:")
for country, count in country_counter.most_common(2):
    print(f"{country}: {count} movies")

    # Visualize the top 10 countries
top_10 = country_counter.most_common(10)
countries, counts = zip(*top_10)

plt.figure(figsize=(10, 6))
plt.barh(countries[::-1], counts[::-1], color='mediumseagreen')
plt.xlabel("Number of Movies Produced")
plt.title(" Top 10 Movie-Producing Countries")
plt.tight_layout()
plt.show()

In [ ]:
# Q11: Find the top 1 company with the highest production movies number

# Parse the 'production_companies' column safely
data['production_companies'] = data['production_companies'].apply(lambda x: eval(x) if isinstance(x, str) else [])

# Extract company names
data['company_names'] = data['production_companies'].apply(lambda x: [d['name'] for d in x if 'name' in d])

# Count all companies
company_counter = Counter()
for company_list in data['company_names']:
    company_counter.update(company_list)

# Show the top 1 company
top_1 = company_counter.most_common(1)
print("Top production company by number of movies:")
for name, count in top_1:
    print(f"{name}: {count} movies")

In [ ]:
# Q12: Is there any relation between the runtime and average vote value

In [ ]:
# Q13: Find the top 5 movies with the highest rate, ?? and find if there anything common between them ??

#Pandas imported 
#ast imported 
#Counter imported from collection 
#Genres already converted in Q7 
#production copines column alredy converted to python in Q 11
#Company names already extracted in Q 11 


# Sort by vote_average in descending order and select the top 5
top_5_rated_movies = data.sort_values(by='vote_average', ascending=False)[['title', 'vote_average', 'vote_count']].head(5).reset_index(drop=True)  #to remove the original file index from the results 

# Display the result
print(top_5_rated_movies)

In [ ]:
# Q14: Find the most unsuccessful movie along time in terms of revenue - budget

#file already loaded
#pandas already imported 

# Ensure 'budget' and 'revenue' are numeric and calculate profit
data['budget'] = pd.to_numeric(data['budget'], errors='coerce')
data['revenue'] = pd.to_numeric(data['revenue'], errors='coerce')
data['profit'] = data['revenue'] - data['budget']

# Find the most unsuccessful movie by maximum negative profit
most_unsuccessful = data.loc[data['profit'].idxmin()]

# Display result
print("Most Unsuccessful Movie:")
print(f"{most_unsuccessful['title']}")

In [ ]:
# Q15: Rearange the dataframe based on vote_average column values

#Make sure vote average are numbers 
data['vote_average'] = pd.to_numeric(data['vote_average'], errors='coerce')

# Sort the DataFrame by vote_average in descending order
sorted_data = data.sort_values(by='vote_average', ascending=False)

# Optionally, reset index
sorted_data.reset_index(drop=True, inplace=True)

# Display the top 5 for verification
print(sorted_data[['title', 'vote_average']].head())

In [ ]:
# Q16: Rearange the dataframe based on runtime column values

# Sort the DataFrame by runtime in ascending order (shortest first)
sorted_by_runtime = data.sort_values(by='runtime', ascending=True)

# Optionally, reset the index
sorted_by_runtime = sorted_by_runtime[sorted_by_runtime['runtime'] > 0].reset_index(drop=True)  #to remove the original file index from the results

# Display the top 5 rows to verify
print(sorted_by_runtime[['title', 'runtime']].head())

In [ ]:
#Find the top 5 successful years for the USA cinema based on the total income devided by number of movies

In [ ]:
#Find the most succesfull movie in [USA, UK]

In [ ]:
#In your opinion what is the highest variable that affects the revenue value (high coloration)